In [1]:
import os
os.environ['CUDA_VISIBLE_DEVICES']='4,5,6,7'

In [ ]:
%run -p ../train_cnf_disentangle_rl_semisup.py --data cifar10 --dims 64,64,64 --strides 1,1,1,1 --num_blocks 2 --layer_type concat --multiscale True --rademacher True --batch_size 900 --test_batch_size 500 --save ../experiments_published/infocnf_cond_cifar10_bs900_sratio_0_5_drop_0_5_rl_stdscale_6_nsup4k_beta_1_run1 --seed 1 --lr 0.001 --conditional True --controlled_tol False --train_mode semisup --log_freq 10 --weight_y 0.5 --condition_ratio 0.5 --dropout_rate 0.5 --scale_fac 1.0 --scale_std 6.0 --labeled_batch_size 450 --num_train_sup 4000 --beta 1.0
#

/tancode/repos/tan-ffjord/train_cnf_disentangle_rl_semisup.py
import argparse
import os
import time
import numpy as np

import torch
import torch.optim as optim
import torchvision.datasets as dset
import torchvision.transforms as tforms
from torchvision.utils import save_image

import torch.utils.data as data
from torch.utils.data import Dataset

import matplotlib.pyplot as plt
plt.rcParams['figure.dpi'] = 300

from PIL import Image
import os.path
import errno
import codecs

import lib.layers as layers
import lib.utils as utils
import lib.multiscale_parallel as multiscale_parallel
import lib.modules as modules
import lib.thops as thops

from train_misc import standard_normal_logprob
from train_misc import set_cnf_options, count_nfe, count_parameters, count_total_time, count_nfe_gate
from train_misc import add_spectral_norm, spectral_norm_power_iteration
from train_misc import create_regularization_fns, get_regularization, append_regularization_to_log

from tensorboardX import SummaryWr

Load semi-sup datasets for CIFAR10


ODENVP(
  (transforms): ModuleList(
    (0): StackedCNFLayers(
      (chain): ModuleList(
        (0): LogitTransform()
        (1): CNF_Gate(
          (gate_net): FeedforwardGateI(
            (maxpool): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
            (conv1): Conv2d(3, 10, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
            (bn1): BatchNorm2d(10, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
            (relu1): ReLU(inplace)
            (conv2): Conv2d(10, 10, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1), bias=False)
            (bn2): BatchNorm2d(10, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
            (relu2): ReLU(inplace)
            (avg_layer): AdaptiveAvgPool2d(output_size=(1, 1))
            (linear_layer): Conv2d(10, 1, kernel_size=(1, 1), stride=(1, 1))
            (sigmoid): Sigmoid()
          )
          (odefunc): RegularizedODEfunc(
            (odefunc): ODEfu

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

Epoch 0001 | Time 245.4578, Epoch Time 1602.0221(1602.0221), Bit/dim 7.0173(best: inf), Bit/dim Marginal 7.0170(best: inf), Xent 2.0832, Loss 8.0589, Error 0.7076(best: inf)
===> Using batch size 900. Total 102 iterations/epoch.
Iter 0110 | Time 14.1054(14.1421) | Bit/dim 6.9789(7.3713) | Xent 2.0808(2.0931) | Loss 18.1506(19.3598) | Error 0.6956(0.7078) Steps 580(522.03) | Grad Norm 8.7332(6.0048) | Total Time 0.00(0.00)
Iter 0120 | Time 14.1051(14.1004) | Bit/dim 6.9533(7.2658) | Xent 2.0297(2.0841) | Loss 17.8148(18.9692) | Error 0.6867(0.7050) Steps 532(526.34) | Grad Norm 3.5184(6.0687) | Total Time 0.00(0.00)
Iter 0130 | Time 14.2262(14.1030) | Bit/dim 6.9220(7.1794) | Xent 2.0018(2.0728) | Loss 17.7786(18.6684) | Error 0.6711(0.7005) Steps 550(531.60) | Grad Norm 4.4391(6.6068) | Total Time 0.00(0.00)
Iter 0140 | Time 14.6627(14.1497) | Bit/dim 6.8954(7.1065) | Xent 1.9783(2.0604) | Loss 17.7073(18.4328) | Error 0.6378(0.6932) Steps 538(536.10) | Grad Norm 4.1642(6.7688) | Total

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

Epoch 0002 | Time 91.8508, Epoch Time 1618.5955(1602.5193), Bit/dim 6.0296(best: 7.0173), Bit/dim Marginal 6.0231(best: 7.0170), Xent 2.0939, Loss 7.0766, Error 0.7695(best: 0.7076)
===> Using batch size 900. Total 102 iterations/epoch.
Iter 0210 | Time 14.0969(13.9177) | Bit/dim 5.9288(6.4171) | Xent 2.0535(2.0409) | Loss 15.7128(17.3803) | Error 0.6978(0.7013) Steps 556(548.15) | Grad Norm 31.4887(43.8333) | Total Time 0.00(0.00)
Iter 0220 | Time 13.8400(13.8857) | Bit/dim 5.8384(6.2716) | Xent 2.0871(2.0318) | Loss 15.6173(16.8968) | Error 0.7800(0.6955) Steps 580(548.69) | Grad Norm 145.7043(45.6012) | Total Time 0.00(0.00)
Iter 0230 | Time 14.4459(14.0029) | Bit/dim 5.8432(6.1980) | Xent 2.0254(2.0474) | Loss 15.5646(16.6346) | Error 0.6467(0.7042) Steps 562(551.48) | Grad Norm 15.0320(58.0906) | Total Time 0.00(0.00)
Iter 0240 | Time 12.9244(13.8238) | Bit/dim 5.7670(6.0950) | Xent 1.9800(2.0366) | Loss 15.2966(16.3064) | Error 0.6933(0.6969) Steps 526(548.13) | Grad Norm 20.2660

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

Epoch 0003 | Time 78.1091, Epoch Time 1491.6849(1599.1943), Bit/dim 5.5597(best: 6.0296), Bit/dim Marginal 5.5374(best: 6.0231), Xent 1.9935, Loss 6.5565, Error 0.7059(best: 0.7076)
===> Using batch size 900. Total 102 iterations/epoch.
Iter 0310 | Time 13.0505(13.4368) | Bit/dim 5.5263(5.6422) | Xent 1.8284(1.8848) | Loss 14.5644(15.5986) | Error 0.5822(0.6244) Steps 532(533.48) | Grad Norm 44.7662(29.9720) | Total Time 0.00(0.00)
Iter 0320 | Time 13.6312(13.3998) | Bit/dim 5.4654(5.6045) | Xent 1.8540(1.8640) | Loss 14.4427(15.3091) | Error 0.6178(0.6176) Steps 574(533.72) | Grad Norm 48.3695(29.8799) | Total Time 0.00(0.00)
Iter 0330 | Time 13.6712(13.3862) | Bit/dim 5.4905(5.5721) | Xent 1.7731(1.8467) | Loss 14.6131(15.0883) | Error 0.6000(0.6111) Steps 556(534.33) | Grad Norm 8.2601(31.1834) | Total Time 0.00(0.00)
Iter 0340 | Time 14.0319(13.4094) | Bit/dim 5.4564(5.5433) | Xent 1.7244(1.8249) | Loss 14.4642(14.9102) | Error 0.5956(0.6054) Steps 586(535.84) | Grad Norm 56.9542(3

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

Epoch 0004 | Time 77.9468, Epoch Time 1539.3561(1597.3992), Bit/dim 5.2290(best: 5.5597), Bit/dim Marginal 5.1908(best: 5.5374), Xent 1.9755, Loss 6.2167, Error 0.6828(best: 0.7059)
===> Using batch size 900. Total 102 iterations/epoch.
Iter 0410 | Time 13.5265(13.8792) | Bit/dim 5.2097(5.3166) | Xent 1.6145(1.7628) | Loss 13.6742(14.8701) | Error 0.5511(0.6015) Steps 556(554.32) | Grad Norm 8.6415(27.1500) | Total Time 0.00(0.00)
Iter 0420 | Time 13.9592(13.9150) | Bit/dim 5.1277(5.2811) | Xent 1.6339(1.7396) | Loss 13.6442(14.5914) | Error 0.5511(0.5912) Steps 544(554.09) | Grad Norm 26.4856(24.0893) | Total Time 0.00(0.00)
Iter 0430 | Time 14.7771(13.9749) | Bit/dim 5.1361(5.2525) | Xent 1.6564(1.7241) | Loss 13.6132(14.3783) | Error 0.5711(0.5870) Steps 580(553.82) | Grad Norm 21.5514(23.7355) | Total Time 0.00(0.00)
Iter 0440 | Time 13.9646(13.9361) | Bit/dim 5.0868(5.2210) | Xent 1.6331(1.7000) | Loss 13.4256(14.1748) | Error 0.5711(0.5788) Steps 526(549.97) | Grad Norm 28.7714(2

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

Epoch 0005 | Time 82.6992, Epoch Time 1614.1623(1597.9021), Bit/dim 4.9554(best: 5.2290), Bit/dim Marginal 4.9108(best: 5.1908), Xent 1.9276, Loss 5.9192, Error 0.6664(best: 0.6828)
===> Using batch size 900. Total 102 iterations/epoch.
Iter 0520 | Time 14.2034(14.3189) | Bit/dim 4.8841(4.9955) | Xent 1.5160(1.6245) | Loss 13.0342(13.8928) | Error 0.5333(0.5616) Steps 532(552.06) | Grad Norm 22.7265(26.4755) | Total Time 0.00(0.00)
Iter 0530 | Time 15.3174(14.4331) | Bit/dim 4.8664(4.9686) | Xent 1.4993(1.5998) | Loss 12.8311(13.6546) | Error 0.5111(0.5535) Steps 526(552.76) | Grad Norm 21.6290(24.2719) | Total Time 0.00(0.00)
Iter 0540 | Time 14.6658(14.4253) | Bit/dim 4.8330(4.9431) | Xent 1.4646(1.5846) | Loss 12.7365(13.4811) | Error 0.5044(0.5493) Steps 574(556.84) | Grad Norm 27.2804(25.1679) | Total Time 0.00(0.00)
Iter 0550 | Time 14.8668(14.5035) | Bit/dim 4.8290(4.9261) | Xent 1.5782(1.5827) | Loss 12.9278(13.3515) | Error 0.5400(0.5484) Steps 580(558.42) | Grad Norm 53.9481(

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

Epoch 0006 | Time 112.2905, Epoch Time 1703.7545(1601.0776), Bit/dim 4.7879(best: 4.9554), Bit/dim Marginal 4.7395(best: 4.9108), Xent 1.9753, Loss 5.7755, Error 0.6866(best: 0.6664)
===> Using batch size 900. Total 102 iterations/epoch.
Iter 0620 | Time 14.4924(14.8103) | Bit/dim 4.7530(4.8220) | Xent 1.5618(1.5798) | Loss 12.8028(13.5341) | Error 0.5444(0.5476) Steps 568(570.08) | Grad Norm 7.7184(25.6687) | Total Time 0.00(0.00)
Iter 0630 | Time 14.9393(14.8423) | Bit/dim 4.7297(4.7970) | Xent 1.5460(1.5663) | Loss 12.6791(13.3092) | Error 0.5133(0.5445) Steps 568(568.92) | Grad Norm 9.9777(22.5125) | Total Time 0.00(0.00)
Iter 0650 | Time 15.2587(15.0279) | Bit/dim 4.6769(4.7545) | Xent 1.5203(1.5255) | Loss 12.6577(12.9763) | Error 0.5133(0.5310) Steps 562(575.03) | Grad Norm 28.0678(22.1644) | Total Time 0.00(0.00)
Iter 0660 | Time 15.0953(15.0139) | Bit/dim 4.6477(4.7334) | Xent 1.5214(1.5169) | Loss 12.5061(12.8526) | Error 0.5400(0.5316) Steps 580(578.30) | Grad Norm 32.5816(2

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

Epoch 0007 | Time 86.4252, Epoch Time 1723.7827(1604.7588), Bit/dim 4.6670(best: 4.7879), Bit/dim Marginal 4.6184(best: 4.7395), Xent 1.8252, Loss 5.5796, Error 0.6438(best: 0.6664)
===> Using batch size 900. Total 102 iterations/epoch.
Iter 0720 | Time 15.1930(15.4996) | Bit/dim 4.6268(4.6554) | Xent 1.3692(1.4581) | Loss 12.2827(13.1300) | Error 0.4889(0.5130) Steps 568(591.07) | Grad Norm 23.8206(25.7912) | Total Time 0.00(0.00)
Iter 0730 | Time 15.6421(15.5424) | Bit/dim 4.6003(4.6449) | Xent 1.3552(1.4466) | Loss 12.4693(12.9358) | Error 0.4956(0.5085) Steps 622(595.55) | Grad Norm 23.7005(26.5340) | Total Time 0.00(0.00)
Iter 0740 | Time 15.4765(15.6150) | Bit/dim 4.5914(4.6327) | Xent 1.3585(1.4416) | Loss 12.1443(12.7690) | Error 0.4933(0.5097) Steps 610(600.04) | Grad Norm 20.8564(26.7397) | Total Time 0.00(0.00)
Iter 0750 | Time 15.7662(15.7466) | Bit/dim 4.5861(4.6211) | Xent 1.4151(1.4291) | Loss 12.1271(12.6395) | Error 0.5022(0.5031) Steps 592(603.33) | Grad Norm 21.4398(

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

Epoch 0008 | Time 114.0401, Epoch Time 1819.6168(1611.2045), Bit/dim 4.5358(best: 4.6670), Bit/dim Marginal 4.4963(best: 4.6184), Xent 1.8395, Loss 5.4555, Error 0.6418(best: 0.6438)
===> Using batch size 900. Total 102 iterations/epoch.
Iter 0820 | Time 15.7305(15.8442) | Bit/dim 4.4815(4.5396) | Xent 1.3584(1.4073) | Loss 12.0921(12.9278) | Error 0.4822(0.4974) Steps 622(618.89) | Grad Norm 15.5669(26.2776) | Total Time 0.00(0.00)
Iter 0830 | Time 15.9151(15.9046) | Bit/dim 4.4908(4.5279) | Xent 1.3961(1.3986) | Loss 12.0831(12.7202) | Error 0.4822(0.4932) Steps 628(617.85) | Grad Norm 18.8950(24.4861) | Total Time 0.00(0.00)
Iter 0840 | Time 15.2490(15.9168) | Bit/dim 4.4643(4.5137) | Xent 1.3560(1.3827) | Loss 11.9287(12.5325) | Error 0.4978(0.4882) Steps 598(620.86) | Grad Norm 6.0871(21.3854) | Total Time 0.00(0.00)
Iter 0850 | Time 15.7449(15.9043) | Bit/dim 4.4465(4.5024) | Xent 1.3039(1.3724) | Loss 12.0221(12.3918) | Error 0.4644(0.4846) Steps 604(621.40) | Grad Norm 21.4005(

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

Epoch 0009 | Time 98.7162, Epoch Time 1784.6145(1616.4068), Bit/dim 4.4050(best: 4.5358), Bit/dim Marginal 4.3730(best: 4.4963), Xent 1.7452, Loss 5.2776, Error 0.6166(best: 0.6418)
===> Using batch size 900. Total 102 iterations/epoch.
Iter 0920 | Time 15.9254(16.0065) | Bit/dim 4.3766(4.4273) | Xent 1.2991(1.3331) | Loss 11.7343(12.6567) | Error 0.4778(0.4716) Steps 586(628.12) | Grad Norm 38.8532(21.5168) | Total Time 0.00(0.00)
Iter 0930 | Time 16.2319(16.0282) | Bit/dim 4.4242(4.4156) | Xent 1.2864(1.3258) | Loss 11.8562(12.4189) | Error 0.4511(0.4679) Steps 628(628.71) | Grad Norm 26.1960(20.9651) | Total Time 0.00(0.00)
Iter 0940 | Time 16.5154(16.0674) | Bit/dim 4.3793(4.4157) | Xent 1.2863(1.3212) | Loss 11.8966(12.2768) | Error 0.4489(0.4663) Steps 622(630.34) | Grad Norm 25.4156(22.1420) | Total Time 0.00(0.00)
Iter 0950 | Time 14.9045(15.9794) | Bit/dim 4.3663(4.4043) | Xent 1.1622(1.3196) | Loss 11.6039(12.1320) | Error 0.4356(0.4672) Steps 598(628.63) | Grad Norm 14.0440(

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

Epoch 0010 | Time 88.0825, Epoch Time 1806.8662(1622.1206), Bit/dim 4.2981(best: 4.4050), Bit/dim Marginal 4.2724(best: 4.3730), Xent 1.7261, Loss 5.1611, Error 0.5934(best: 0.6166)
===> Using batch size 900. Total 102 iterations/epoch.
Iter 1030 | Time 15.9009(16.0119) | Bit/dim 4.3100(4.3204) | Xent 1.1633(1.2472) | Loss 11.3895(12.1710) | Error 0.4222(0.4451) Steps 628(632.61) | Grad Norm 12.6601(17.5085) | Total Time 0.00(0.00)
Iter 1040 | Time 16.3854(16.0333) | Bit/dim 4.3164(4.3108) | Xent 1.3173(1.2485) | Loss 11.5361(11.9950) | Error 0.4467(0.4451) Steps 592(629.72) | Grad Norm 28.0277(18.7422) | Total Time 0.00(0.00)
Iter 1050 | Time 15.7213(16.0398) | Bit/dim 4.2923(4.3036) | Xent 1.3699(1.2511) | Loss 11.6477(11.8863) | Error 0.4667(0.4431) Steps 604(628.98) | Grad Norm 25.2426(19.7142) | Total Time 0.00(0.00)
Iter 1060 | Time 15.9821(16.0667) | Bit/dim 4.2777(4.2962) | Xent 1.1806(1.2507) | Loss 11.5313(11.7892) | Error 0.4333(0.4428) Steps 640(631.57) | Grad Norm 11.5891(

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

Epoch 0011 | Time 89.4173, Epoch Time 1872.8471(1629.6424), Bit/dim 4.2035(best: 4.2981), Bit/dim Marginal 4.1838(best: 4.2724), Xent 1.6498, Loss 5.0284, Error 0.5775(best: 0.5934)
===> Using batch size 900. Total 102 iterations/epoch.
Iter 1130 | Time 15.6760(16.2040) | Bit/dim 4.1719(4.2205) | Xent 1.1804(1.1746) | Loss 11.0512(11.9221) | Error 0.3756(0.4159) Steps 598(630.45) | Grad Norm 21.3853(15.7718) | Total Time 0.00(0.00)
Iter 1140 | Time 17.3350(16.2714) | Bit/dim 4.1940(4.2096) | Xent 1.0813(1.1640) | Loss 11.2135(11.7323) | Error 0.3578(0.4139) Steps 658(630.99) | Grad Norm 11.8528(14.7893) | Total Time 0.00(0.00)
Iter 1150 | Time 16.2126(16.2598) | Bit/dim 4.1643(4.2001) | Xent 1.0834(1.1451) | Loss 11.0789(11.5601) | Error 0.3867(0.4061) Steps 652(629.96) | Grad Norm 10.4499(14.1400) | Total Time 0.00(0.00)
Iter 1160 | Time 15.6558(16.3555) | Bit/dim 4.1678(4.1928) | Xent 1.0565(1.1385) | Loss 11.1465(11.4648) | Error 0.3844(0.4049) Steps 604(632.51) | Grad Norm 24.6771(