In [1]:
import os
os.environ['CUDA_VISIBLE_DEVICES']='0,1,2,3'

In [ ]:
%run -p ../train_cnf_disentangle_rl_semisup.py --data cifar10 --dims 64,64,64 --strides 1,1,1,1 --num_blocks 2 --layer_type concat --multiscale True --rademacher True --batch_size 900 --test_batch_size 500 --save ../experiments_published/infocnf_cond_cifar10_bs900_sratio_0_5_drop_0_5_rl_stdscale_6_nsup4k_beta_0_001_run1 --seed 1 --lr 0.001 --conditional True --controlled_tol False --train_mode semisup --log_freq 10 --weight_y 0.5 --condition_ratio 0.5 --dropout_rate 0.5 --scale_fac 1.0 --scale_std 6.0 --labeled_batch_size 450 --num_train_sup 4000 --beta 0.001
#

/tancode/repos/tan-ffjord/train_cnf_disentangle_rl_semisup.py
import argparse
import os
import time
import numpy as np

import torch
import torch.optim as optim
import torchvision.datasets as dset
import torchvision.transforms as tforms
from torchvision.utils import save_image

import torch.utils.data as data
from torch.utils.data import Dataset

import matplotlib.pyplot as plt
plt.rcParams['figure.dpi'] = 300

from PIL import Image
import os.path
import errno
import codecs

import lib.layers as layers
import lib.utils as utils
import lib.multiscale_parallel as multiscale_parallel
import lib.modules as modules
import lib.thops as thops

from train_misc import standard_normal_logprob
from train_misc import set_cnf_options, count_nfe, count_parameters, count_total_time, count_nfe_gate
from train_misc import add_spectral_norm, spectral_norm_power_iteration
from train_misc import create_regularization_fns, get_regularization, append_regularization_to_log

from tensorboardX import SummaryWr

Load semi-sup datasets for CIFAR10


ODENVP(
  (transforms): ModuleList(
    (0): StackedCNFLayers(
      (chain): ModuleList(
        (0): LogitTransform()
        (1): CNF_Gate(
          (gate_net): FeedforwardGateI(
            (maxpool): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
            (conv1): Conv2d(3, 10, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
            (bn1): BatchNorm2d(10, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
            (relu1): ReLU(inplace)
            (conv2): Conv2d(10, 10, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1), bias=False)
            (bn2): BatchNorm2d(10, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
            (relu2): ReLU(inplace)
            (avg_layer): AdaptiveAvgPool2d(output_size=(1, 1))
            (linear_layer): Conv2d(10, 1, kernel_size=(1, 1), stride=(1, 1))
            (sigmoid): Sigmoid()
          )
          (odefunc): RegularizedODEfunc(
            (odefunc): ODEfu

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

Epoch 0001 | Time 98.3373, Epoch Time 1560.0854(1560.0854), Bit/dim 7.0173(best: inf), Bit/dim Marginal 7.0170(best: inf), Xent 2.0832, Loss 8.0589, Error 0.7076(best: inf)
===> Using batch size 900. Total 102 iterations/epoch.
Iter 0110 | Time 13.5878(13.7929) | Bit/dim 6.9789(7.3713) | Xent 2.0808(2.0931) | Loss 18.1512(19.3632) | Error 0.6956(0.7078) Steps 544(522.35) | Grad Norm 8.7327(6.0049) | Total Time 0.00(0.00)
Iter 0120 | Time 13.2595(13.7336) | Bit/dim 6.9533(7.2658) | Xent 2.0297(2.0841) | Loss 17.7941(18.9701) | Error 0.6867(0.7050) Steps 538(526.75) | Grad Norm 3.5179(6.0689) | Total Time 0.00(0.00)
Iter 0130 | Time 14.3717(13.8048) | Bit/dim 6.9220(7.1794) | Xent 2.0018(2.0728) | Loss 17.7687(18.6701) | Error 0.6711(0.7005) Steps 544(533.93) | Grad Norm 4.4384(6.6068) | Total Time 0.00(0.00)
Iter 0140 | Time 14.2905(13.7746) | Bit/dim 6.8954(7.1065) | Xent 1.9783(2.0604) | Loss 17.7025(18.4345) | Error 0.6378(0.6932) Steps 574(538.01) | Grad Norm 4.1636(6.7687) | Total 

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

Epoch 0002 | Time 92.2844, Epoch Time 1560.8476(1560.1083), Bit/dim 6.0292(best: 7.0173), Bit/dim Marginal 6.0227(best: 7.0170), Xent 2.0933, Loss 7.0759, Error 0.7693(best: 0.7076)
===> Using batch size 900. Total 102 iterations/epoch.
Iter 0210 | Time 13.0694(13.5932) | Bit/dim 5.9280(6.4169) | Xent 2.0531(2.0409) | Loss 15.7203(17.3876) | Error 0.6956(0.7011) Steps 526(547.74) | Grad Norm 31.6222(43.8816) | Total Time 0.00(0.00)
Iter 0220 | Time 13.6020(13.5402) | Bit/dim 5.8366(6.2714) | Xent 2.0881(2.0319) | Loss 15.6127(16.9028) | Error 0.7822(0.6953) Steps 532(548.30) | Grad Norm 143.7221(45.5573) | Total Time 0.00(0.00)
Iter 0230 | Time 13.7457(13.5779) | Bit/dim 5.8434(6.1957) | Xent 2.0282(2.0467) | Loss 15.5563(16.6329) | Error 0.6600(0.7040) Steps 532(550.67) | Grad Norm 19.9468(57.8066) | Total Time 0.00(0.00)
Iter 0240 | Time 13.0369(13.4563) | Bit/dim 5.7619(6.0918) | Xent 1.9796(2.0360) | Loss 15.2786(16.3016) | Error 0.6933(0.6965) Steps 568(548.29) | Grad Norm 19.5892

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

Epoch 0003 | Time 82.1273, Epoch Time 1449.5027(1556.7901), Bit/dim 5.5605(best: 6.0292), Bit/dim Marginal 5.5381(best: 6.0227), Xent 1.9924, Loss 6.5567, Error 0.6911(best: 0.7076)
===> Using batch size 900. Total 102 iterations/epoch.
Iter 0310 | Time 12.7672(13.0299) | Bit/dim 5.5183(5.6415) | Xent 1.8126(1.8843) | Loss 14.5165(15.5875) | Error 0.5756(0.6257) Steps 520(531.45) | Grad Norm 22.0194(30.7555) | Total Time 0.00(0.00)
Iter 0320 | Time 13.0896(13.0002) | Bit/dim 5.4541(5.6060) | Xent 1.8398(1.8723) | Loss 14.4229(15.3163) | Error 0.5800(0.6237) Steps 514(531.53) | Grad Norm 11.9971(33.6692) | Total Time 0.00(0.00)
Iter 0330 | Time 13.3378(12.9990) | Bit/dim 5.4910(5.5718) | Xent 1.7814(1.8532) | Loss 14.6106(15.0904) | Error 0.6133(0.6144) Steps 550(531.29) | Grad Norm 13.0646(30.4754) | Total Time 0.00(0.00)
Iter 0340 | Time 14.1605(13.0495) | Bit/dim 5.4580(5.5422) | Xent 1.6905(1.8279) | Loss 14.4330(14.9085) | Error 0.5644(0.6056) Steps 586(533.76) | Grad Norm 41.2701(

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

Epoch 0004 | Time 83.2158, Epoch Time 1504.0277(1555.2072), Bit/dim 5.2147(best: 5.5605), Bit/dim Marginal 5.1756(best: 5.5381), Xent 1.9414, Loss 6.1854, Error 0.6700(best: 0.6911)
===> Using batch size 900. Total 102 iterations/epoch.
Iter 0410 | Time 14.0628(13.4779) | Bit/dim 5.2099(5.3074) | Xent 1.5807(1.7452) | Loss 13.6579(14.8420) | Error 0.5244(0.5871) Steps 556(550.29) | Grad Norm 20.1116(20.7655) | Total Time 0.00(0.00)
Iter 0420 | Time 13.3593(13.5103) | Bit/dim 5.1230(5.2713) | Xent 1.6065(1.7194) | Loss 13.6367(14.5622) | Error 0.5467(0.5798) Steps 556(552.40) | Grad Norm 17.7052(19.8412) | Total Time 0.00(0.00)
Iter 0430 | Time 13.7112(13.5099) | Bit/dim 5.1265(5.2424) | Xent 1.6396(1.7023) | Loss 13.6068(14.3501) | Error 0.5533(0.5762) Steps 586(554.50) | Grad Norm 18.2808(19.6117) | Total Time 0.00(0.00)
Iter 0440 | Time 12.9885(13.4886) | Bit/dim 5.0850(5.2118) | Xent 1.6046(1.6782) | Loss 13.4123(14.1491) | Error 0.5489(0.5694) Steps 532(553.48) | Grad Norm 26.9605(

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

Epoch 0005 | Time 81.9085, Epoch Time 1584.0427(1556.0723), Bit/dim 4.9538(best: 5.2147), Bit/dim Marginal 4.9098(best: 5.1756), Xent 1.9117, Loss 5.9096, Error 0.6638(best: 0.6700)
===> Using batch size 900. Total 102 iterations/epoch.
Iter 0520 | Time 14.3479(13.9661) | Bit/dim 4.8952(4.9861) | Xent 1.5749(1.6103) | Loss 13.1340(13.8674) | Error 0.5533(0.5573) Steps 532(550.82) | Grad Norm 43.5319(32.2199) | Total Time 0.00(0.00)
Iter 0530 | Time 14.7224(14.0658) | Bit/dim 4.9033(4.9665) | Xent 1.5248(1.5998) | Loss 12.9679(13.6591) | Error 0.5311(0.5536) Steps 580(552.82) | Grad Norm 37.3284(32.3141) | Total Time 0.00(0.00)
Iter 0550 | Time 15.3012(14.2918) | Bit/dim 4.8033(4.9154) | Xent 1.4713(1.5714) | Loss 12.7666(13.3209) | Error 0.4822(0.5437) Steps 610(560.83) | Grad Norm 29.7502(29.9292) | Total Time 0.00(0.00)
Iter 0560 | Time 13.9680(14.3954) | Bit/dim 4.8707(4.8914) | Xent 1.5946(1.5655) | Loss 12.9915(13.2002) | Error 0.5489(0.5439) Steps 574(564.35) | Grad Norm 64.2704(

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

Epoch 0006 | Time 112.5411, Epoch Time 1698.7823(1560.3536), Bit/dim 4.7840(best: 4.9538), Bit/dim Marginal 4.7364(best: 4.9098), Xent 1.9001, Loss 5.7341, Error 0.6703(best: 0.6638)
===> Using batch size 900. Total 102 iterations/epoch.
Iter 0620 | Time 14.5869(14.7645) | Bit/dim 4.7664(4.7991) | Xent 1.5960(1.5265) | Loss 12.9245(13.4595) | Error 0.5533(0.5336) Steps 574(577.10) | Grad Norm 47.9249(33.6650) | Total Time 0.00(0.00)
Iter 0630 | Time 14.9722(14.8476) | Bit/dim 4.7387(4.7824) | Xent 1.6343(1.5445) | Loss 12.8211(13.2829) | Error 0.5622(0.5396) Steps 568(578.24) | Grad Norm 33.9881(34.1506) | Total Time 0.00(0.00)
Iter 0640 | Time 14.2651(14.8538) | Bit/dim 4.7319(4.7691) | Xent 1.4830(1.5326) | Loss 12.5934(13.1097) | Error 0.5311(0.5352) Steps 526(574.26) | Grad Norm 25.6420(33.1502) | Total Time 0.00(0.00)
Iter 0650 | Time 15.1260(14.8454) | Bit/dim 4.6488(4.7505) | Xent 1.4201(1.5144) | Loss 12.4668(12.9665) | Error 0.5067(0.5278) Steps 592(570.90) | Grad Norm 8.3534(

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

Epoch 0007 | Time 83.1441, Epoch Time 1703.1577(1564.6377), Bit/dim 4.6408(best: 4.7840), Bit/dim Marginal 4.5949(best: 4.7364), Xent 1.8838, Loss 5.5827, Error 0.6592(best: 0.6638)
===> Using batch size 900. Total 102 iterations/epoch.
Iter 0720 | Time 15.3979(15.1267) | Bit/dim 4.6245(4.6589) | Xent 1.3994(1.4650) | Loss 12.3142(13.1492) | Error 0.4800(0.5160) Steps 574(586.80) | Grad Norm 18.3843(29.9308) | Total Time 0.00(0.00)
Iter 0730 | Time 15.6154(15.1470) | Bit/dim 4.6062(4.6451) | Xent 1.3762(1.4524) | Loss 12.5176(12.9463) | Error 0.5089(0.5100) Steps 634(591.39) | Grad Norm 30.2349(29.0327) | Total Time 0.00(0.00)
Iter 0740 | Time 15.4913(15.2287) | Bit/dim 4.5888(4.6324) | Xent 1.3681(1.4412) | Loss 12.1679(12.7738) | Error 0.4867(0.5074) Steps 568(592.35) | Grad Norm 22.7638(27.1509) | Total Time 0.00(0.00)
Iter 0750 | Time 15.2771(15.2580) | Bit/dim 4.5705(4.6181) | Xent 1.4067(1.4226) | Loss 12.0793(12.6315) | Error 0.4867(0.4995) Steps 562(593.29) | Grad Norm 17.2701(

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

Epoch 0008 | Time 84.3280, Epoch Time 1700.4818(1568.7130), Bit/dim 4.5667(best: 4.6408), Bit/dim Marginal 4.5267(best: 4.5949), Xent 1.8434, Loss 5.4883, Error 0.6401(best: 0.6592)
===> Using batch size 900. Total 102 iterations/epoch.
Iter 0820 | Time 15.1505(15.1116) | Bit/dim 4.4995(4.5562) | Xent 1.3344(1.4121) | Loss 12.0857(12.9253) | Error 0.4711(0.4961) Steps 568(595.14) | Grad Norm 15.2462(23.2746) | Total Time 0.00(0.00)
Iter 0830 | Time 15.2306(15.1075) | Bit/dim 4.4814(4.5418) | Xent 1.3682(1.3980) | Loss 12.0109(12.7117) | Error 0.4889(0.4909) Steps 604(596.82) | Grad Norm 14.3784(21.6717) | Total Time 0.00(0.00)
Iter 0840 | Time 14.5962(15.1230) | Bit/dim 4.4797(4.5252) | Xent 1.3703(1.3826) | Loss 11.9318(12.5176) | Error 0.4844(0.4853) Steps 580(595.91) | Grad Norm 15.5821(19.3273) | Total Time 0.00(0.00)
Iter 0850 | Time 15.9425(15.1577) | Bit/dim 4.4504(4.5099) | Xent 1.2817(1.3687) | Loss 11.9679(12.3661) | Error 0.4511(0.4805) Steps 628(596.04) | Grad Norm 12.4961(

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

Epoch 0009 | Time 93.6513, Epoch Time 1688.5339(1572.3077), Bit/dim 4.4714(best: 4.5667), Bit/dim Marginal 4.4375(best: 4.5267), Xent 1.8440, Loss 5.3934, Error 0.6512(best: 0.6401)
===> Using batch size 900. Total 102 iterations/epoch.
Iter 0920 | Time 14.3697(15.0435) | Bit/dim 4.3962(4.4482) | Xent 1.3076(1.3461) | Loss 11.7214(12.6794) | Error 0.4644(0.4721) Steps 574(595.06) | Grad Norm 25.6140(22.8139) | Total Time 0.00(0.00)
Iter 0930 | Time 15.0649(14.9399) | Bit/dim 4.4212(4.4370) | Xent 1.2814(1.3407) | Loss 11.8083(12.4358) | Error 0.4444(0.4694) Steps 604(590.64) | Grad Norm 14.0110(21.3531) | Total Time 0.00(0.00)
Iter 0940 | Time 14.8105(14.9776) | Bit/dim 4.3770(4.4233) | Xent 1.2221(1.3232) | Loss 11.8024(12.2491) | Error 0.4200(0.4659) Steps 598(591.13) | Grad Norm 14.7769(19.6575) | Total Time 0.00(0.00)
Iter 0950 | Time 14.7761(14.9801) | Bit/dim 4.3646(4.4065) | Xent 1.1438(1.3071) | Loss 11.5931(12.0872) | Error 0.4156(0.4611) Steps 598(594.92) | Grad Norm 11.3419(

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

Epoch 0010 | Time 86.6552, Epoch Time 1688.2605(1575.7862), Bit/dim 4.3064(best: 4.4714), Bit/dim Marginal 4.2804(best: 4.4375), Xent 1.6923, Loss 5.1525, Error 0.5963(best: 0.6401)
===> Using batch size 900. Total 102 iterations/epoch.
Iter 1030 | Time 15.0349(14.9623) | Bit/dim 4.3127(4.3360) | Xent 1.1612(1.2489) | Loss 11.3357(12.1557) | Error 0.3956(0.4441) Steps 550(591.55) | Grad Norm 10.3908(15.3535) | Total Time 0.00(0.00)
Iter 1040 | Time 14.8749(14.9795) | Bit/dim 4.2786(4.3196) | Xent 1.3372(1.2477) | Loss 11.4359(11.9663) | Error 0.4644(0.4439) Steps 556(588.50) | Grad Norm 30.7584(15.9803) | Total Time 0.00(0.00)
Iter 1050 | Time 14.8721(15.0361) | Bit/dim 4.2902(4.3153) | Xent 1.2742(1.2396) | Loss 11.5425(11.8596) | Error 0.4533(0.4401) Steps 574(592.76) | Grad Norm 18.9550(18.0330) | Total Time 0.00(0.00)
Iter 1060 | Time 15.0392(15.0385) | Bit/dim 4.2793(4.3051) | Xent 1.1606(1.2343) | Loss 11.4985(11.7555) | Error 0.4089(0.4392) Steps 634(593.48) | Grad Norm 9.1401(1

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

Epoch 0011 | Time 82.8374, Epoch Time 1719.3500(1580.0932), Bit/dim 4.2174(best: 4.3064), Bit/dim Marginal 4.1975(best: 4.2804), Xent 1.6326, Loss 5.0337, Error 0.5762(best: 0.5963)
===> Using batch size 900. Total 102 iterations/epoch.
Iter 1130 | Time 15.5043(15.3202) | Bit/dim 4.1785(4.2336) | Xent 1.1740(1.1735) | Loss 11.0134(11.8833) | Error 0.3933(0.4180) Steps 538(597.45) | Grad Norm 20.3663(15.4776) | Total Time 0.00(0.00)
Iter 1140 | Time 15.9599(15.3964) | Bit/dim 4.1971(4.2232) | Xent 1.1378(1.1667) | Loss 11.1945(11.7079) | Error 0.3956(0.4167) Steps 568(599.00) | Grad Norm 19.5740(15.7234) | Total Time 0.00(0.00)
Iter 1150 | Time 16.1205(15.4225) | Bit/dim 4.1807(4.2131) | Xent 1.1016(1.1548) | Loss 11.1218(11.5509) | Error 0.4000(0.4105) Steps 610(598.26) | Grad Norm 12.3763(15.6350) | Total Time 0.00(0.00)
Iter 1160 | Time 14.9888(15.4610) | Bit/dim 4.1993(4.2078) | Xent 1.0827(1.1546) | Loss 11.2060(11.4696) | Error 0.3911(0.4114) Steps 580(603.06) | Grad Norm 18.4461(