In [1]:
import os
os.environ['CUDA_VISIBLE_DEVICES']='4,5,6,7'

In [ ]:
%run -p ../train_cnf_disentangle_rl_semisup.py --data cifar10 --dims 64,64,64 --strides 1,1,1,1 --num_blocks 2 --layer_type concat --multiscale True --rademacher True --batch_size 900 --test_batch_size 500 --save ../experiments_published/infocnf_cond_cifar10_bs900_sratio_0_5_drop_0_5_rl_stdscale_6_nsup4k_beta_0_0001_run1 --seed 1 --lr 0.001 --conditional True --controlled_tol False --train_mode semisup --log_freq 10 --weight_y 0.5 --condition_ratio 0.5 --dropout_rate 0.5 --scale_fac 1.0 --scale_std 6.0 --labeled_batch_size 450 --num_train_sup 4000 --beta 0.0001
#

/tancode/repos/tan-ffjord/train_cnf_disentangle_rl_semisup.py
import argparse
import os
import time
import numpy as np

import torch
import torch.optim as optim
import torchvision.datasets as dset
import torchvision.transforms as tforms
from torchvision.utils import save_image

import torch.utils.data as data
from torch.utils.data import Dataset

import matplotlib.pyplot as plt
plt.rcParams['figure.dpi'] = 300

from PIL import Image
import os.path
import errno
import codecs

import lib.layers as layers
import lib.utils as utils
import lib.multiscale_parallel as multiscale_parallel
import lib.modules as modules
import lib.thops as thops

from train_misc import standard_normal_logprob
from train_misc import set_cnf_options, count_nfe, count_parameters, count_total_time, count_nfe_gate
from train_misc import add_spectral_norm, spectral_norm_power_iteration
from train_misc import create_regularization_fns, get_regularization, append_regularization_to_log

from tensorboardX import SummaryWr

Load semi-sup datasets for CIFAR10


ODENVP(
  (transforms): ModuleList(
    (0): StackedCNFLayers(
      (chain): ModuleList(
        (0): LogitTransform()
        (1): CNF_Gate(
          (gate_net): FeedforwardGateI(
            (maxpool): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
            (conv1): Conv2d(3, 10, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
            (bn1): BatchNorm2d(10, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
            (relu1): ReLU(inplace)
            (conv2): Conv2d(10, 10, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1), bias=False)
            (bn2): BatchNorm2d(10, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
            (relu2): ReLU(inplace)
            (avg_layer): AdaptiveAvgPool2d(output_size=(1, 1))
            (linear_layer): Conv2d(10, 1, kernel_size=(1, 1), stride=(1, 1))
            (sigmoid): Sigmoid()
          )
          (odefunc): RegularizedODEfunc(
            (odefunc): ODEfu

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

Epoch 0001 | Time 99.5254, Epoch Time 1681.1855(1681.1855), Bit/dim 7.0173(best: inf), Bit/dim Marginal 7.0170(best: inf), Xent 2.0832, Loss 8.0589, Error 0.7075(best: inf)
===> Using batch size 900. Total 102 iterations/epoch.
Iter 0110 | Time 12.6726(13.6710) | Bit/dim 6.9789(7.3713) | Xent 2.0808(2.0931) | Loss 18.1510(19.3613) | Error 0.6956(0.7077) Steps 550(523.97) | Grad Norm 8.7338(6.0051) | Total Time 0.00(0.00)
Iter 0120 | Time 13.8107(13.6052) | Bit/dim 6.9533(7.2658) | Xent 2.0297(2.0841) | Loss 17.8145(18.9691) | Error 0.6867(0.7049) Steps 544(528.02) | Grad Norm 3.5186(6.0690) | Total Time 0.00(0.00)
Iter 0130 | Time 13.4047(13.5958) | Bit/dim 6.9220(7.1794) | Xent 2.0018(2.0728) | Loss 17.7593(18.6680) | Error 0.6711(0.7004) Steps 556(533.07) | Grad Norm 4.4387(6.6069) | Total Time 0.00(0.00)
Iter 0140 | Time 14.0782(13.6069) | Bit/dim 6.8954(7.1065) | Xent 1.9783(2.0604) | Loss 17.7059(18.4326) | Error 0.6378(0.6931) Steps 526(537.44) | Grad Norm 4.1644(6.7688) | Total 

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

Epoch 0002 | Time 119.7178, Epoch Time 1562.1711(1677.6151), Bit/dim 6.0295(best: 7.0173), Bit/dim Marginal 6.0229(best: 7.0170), Xent 2.0937, Loss 7.0763, Error 0.7701(best: 0.7075)
===> Using batch size 900. Total 102 iterations/epoch.
Iter 0210 | Time 13.6011(13.5338) | Bit/dim 5.9287(6.4170) | Xent 2.0538(2.0410) | Loss 15.7214(17.3846) | Error 0.6956(0.7011) Steps 550(545.89) | Grad Norm 31.6986(43.8608) | Total Time 0.00(0.00)
Iter 0220 | Time 13.7339(13.4943) | Bit/dim 5.8449(6.2718) | Xent 2.0999(2.0324) | Loss 15.6435(16.9016) | Error 0.7933(0.6959) Steps 526(545.45) | Grad Norm 154.1916(46.0255) | Total Time 0.00(0.00)
Iter 0230 | Time 13.8406(13.5522) | Bit/dim 5.8345(6.1955) | Xent 2.0255(2.0464) | Loss 15.5349(16.6303) | Error 0.6489(0.7044) Steps 574(548.49) | Grad Norm 15.0207(57.9291) | Total Time 0.00(0.00)
Iter 0240 | Time 12.5627(13.3933) | Bit/dim 5.7634(6.0912) | Xent 1.9808(2.0363) | Loss 15.2979(16.2990) | Error 0.7000(0.6980) Steps 550(545.62) | Grad Norm 21.418

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

Epoch 0003 | Time 84.2315, Epoch Time 1449.4854(1670.7712), Bit/dim 5.5577(best: 6.0295), Bit/dim Marginal 5.5352(best: 6.0229), Xent 1.9786, Loss 6.5470, Error 0.6840(best: 0.7075)
===> Using batch size 900. Total 102 iterations/epoch.
Iter 0310 | Time 12.7063(13.0202) | Bit/dim 5.5237(5.6408) | Xent 1.8222(1.8813) | Loss 14.5367(15.5740) | Error 0.6000(0.6236) Steps 508(536.74) | Grad Norm 35.4421(29.2660) | Total Time 0.00(0.00)
Iter 0320 | Time 12.9766(13.0118) | Bit/dim 5.4601(5.6092) | Xent 1.8607(1.8847) | Loss 14.4456(15.3290) | Error 0.5956(0.6295) Steps 562(536.98) | Grad Norm 12.7003(36.5709) | Total Time 0.00(0.00)
Iter 0330 | Time 12.6588(12.9582) | Bit/dim 5.4977(5.5759) | Xent 1.8572(1.8762) | Loss 14.7181(15.1183) | Error 0.6644(0.6267) Steps 550(537.61) | Grad Norm 28.6736(34.6912) | Total Time 0.00(0.00)
Iter 0340 | Time 13.8890(12.9387) | Bit/dim 5.4447(5.5440) | Xent 1.7076(1.8534) | Loss 14.4243(14.9359) | Error 0.5689(0.6144) Steps 538(536.04) | Grad Norm 18.7108(

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

Epoch 0004 | Time 92.8339, Epoch Time 1467.8576(1664.6838), Bit/dim 5.2222(best: 5.5577), Bit/dim Marginal 5.1794(best: 5.5352), Xent 1.9366, Loss 6.1905, Error 0.6684(best: 0.6840)
===> Using batch size 900. Total 102 iterations/epoch.
Iter 0410 | Time 13.8058(13.4925) | Bit/dim 5.2009(5.3050) | Xent 1.6210(1.7299) | Loss 13.6692(14.8137) | Error 0.5467(0.5866) Steps 550(554.40) | Grad Norm 24.1740(29.1339) | Total Time 0.00(0.00)
Iter 0420 | Time 13.3099(13.5101) | Bit/dim 5.1228(5.2694) | Xent 1.6260(1.7087) | Loss 13.6492(14.5401) | Error 0.5667(0.5796) Steps 550(553.04) | Grad Norm 28.2290(26.4030) | Total Time 0.00(0.00)
Iter 0430 | Time 14.8277(13.5254) | Bit/dim 5.1256(5.2408) | Xent 1.6441(1.6950) | Loss 13.6025(14.3310) | Error 0.5711(0.5762) Steps 586(555.72) | Grad Norm 18.9029(24.7063) | Total Time 0.00(0.00)
Iter 0440 | Time 12.4429(13.4231) | Bit/dim 5.1014(5.2142) | Xent 1.6005(1.6744) | Loss 13.4247(14.1417) | Error 0.5533(0.5705) Steps 526(554.03) | Grad Norm 31.1677(

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

Epoch 0005 | Time 76.6991, Epoch Time 1498.8367(1659.7084), Bit/dim 4.9592(best: 5.2222), Bit/dim Marginal 4.9157(best: 5.1794), Xent 1.9312, Loss 5.9248, Error 0.6751(best: 0.6684)
===> Using batch size 900. Total 102 iterations/epoch.
Iter 0520 | Time 14.0335(13.7323) | Bit/dim 4.8726(4.9903) | Xent 1.5048(1.5957) | Loss 13.0156(13.8484) | Error 0.5356(0.5509) Steps 538(549.88) | Grad Norm 21.4122(26.4405) | Total Time 0.00(0.00)
Iter 0530 | Time 13.6198(13.8476) | Bit/dim 4.8576(4.9636) | Xent 1.4662(1.5720) | Loss 12.7977(13.6132) | Error 0.4933(0.5436) Steps 544(551.70) | Grad Norm 18.9521(24.7407) | Total Time 0.00(0.00)
Iter 0540 | Time 13.6624(13.8734) | Bit/dim 4.9710(4.9527) | Xent 1.5334(1.5796) | Loss 13.0863(13.4939) | Error 0.5200(0.5457) Steps 520(554.38) | Grad Norm 52.4004(32.0512) | Total Time 0.00(0.00)
Iter 0550 | Time 14.5100(13.9205) | Bit/dim 4.8747(4.9511) | Xent 1.6415(1.6325) | Loss 13.0769(13.4523) | Error 0.5578(0.5652) Steps 562(555.73) | Grad Norm 17.1542(

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

Epoch 0006 | Time 83.5678, Epoch Time 1607.3236(1658.1368), Bit/dim 4.7701(best: 4.9592), Bit/dim Marginal 4.7122(best: 4.9157), Xent 1.9258, Loss 5.7330, Error 0.6720(best: 0.6684)
===> Using batch size 900. Total 102 iterations/epoch.
Iter 0620 | Time 14.1273(14.3263) | Bit/dim 4.7546(4.7926) | Xent 1.5665(1.5359) | Loss 12.8651(13.4320) | Error 0.5556(0.5390) Steps 580(563.60) | Grad Norm 50.0892(26.4380) | Total Time 0.00(0.00)
Iter 0630 | Time 15.1045(14.4846) | Bit/dim 4.7498(4.7804) | Xent 1.5119(1.5315) | Loss 12.7271(13.2513) | Error 0.5133(0.5372) Steps 574(568.70) | Grad Norm 22.6564(27.3433) | Total Time 0.00(0.00)
Iter 0640 | Time 14.4888(14.5183) | Bit/dim 4.7287(4.7653) | Xent 1.4568(1.5212) | Loss 12.6194(13.0867) | Error 0.5311(0.5329) Steps 580(571.01) | Grad Norm 21.6566(28.1861) | Total Time 0.00(0.00)
Iter 0650 | Time 14.5370(14.5517) | Bit/dim 4.6951(4.7538) | Xent 1.4259(1.5075) | Loss 12.5811(12.9679) | Error 0.4844(0.5282) Steps 592(574.23) | Grad Norm 15.9194(

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,