In [1]:
import os
os.environ['CUDA_VISIBLE_DEVICES']='0,1,2,3'

In [ ]:
%run -p ../train_cnf_disentangle_rl_semisup.py --data cifar10 --dims 64,64,64 --strides 1,1,1,1 --num_blocks 2 --layer_type concat --multiscale True --rademacher True --batch_size 900 --test_batch_size 500 --save ../experiments_published/infocnf_cond_cifar10_bs900_sratio_0_5_drop_0_5_rl_stdscale_6_nsup4k_beta_1000_run1 --seed 1 --lr 0.001 --conditional True --controlled_tol False --train_mode semisup --log_freq 10 --weight_y 0.5 --condition_ratio 0.5 --dropout_rate 0.5 --scale_fac 1.0 --scale_std 6.0 --labeled_batch_size 450 --num_train_sup 4000 --beta 1000.0
#

/tancode/repos/tan-ffjord/train_cnf_disentangle_rl_semisup.py
import argparse
import os
import time
import numpy as np

import torch
import torch.optim as optim
import torchvision.datasets as dset
import torchvision.transforms as tforms
from torchvision.utils import save_image

import torch.utils.data as data
from torch.utils.data import Dataset

import matplotlib.pyplot as plt
plt.rcParams['figure.dpi'] = 300

from PIL import Image
import os.path
import errno
import codecs

import lib.layers as layers
import lib.utils as utils
import lib.multiscale_parallel as multiscale_parallel
import lib.modules as modules
import lib.thops as thops

from train_misc import standard_normal_logprob
from train_misc import set_cnf_options, count_nfe, count_parameters, count_total_time, count_nfe_gate
from train_misc import add_spectral_norm, spectral_norm_power_iteration
from train_misc import create_regularization_fns, get_regularization, append_regularization_to_log

from tensorboardX import SummaryWr

Load semi-sup datasets for CIFAR10


ODENVP(
  (transforms): ModuleList(
    (0): StackedCNFLayers(
      (chain): ModuleList(
        (0): LogitTransform()
        (1): CNF_Gate(
          (gate_net): FeedforwardGateI(
            (maxpool): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
            (conv1): Conv2d(3, 10, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
            (bn1): BatchNorm2d(10, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
            (relu1): ReLU(inplace)
            (conv2): Conv2d(10, 10, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1), bias=False)
            (bn2): BatchNorm2d(10, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
            (relu2): ReLU(inplace)
            (avg_layer): AdaptiveAvgPool2d(output_size=(1, 1))
            (linear_layer): Conv2d(10, 1, kernel_size=(1, 1), stride=(1, 1))
            (sigmoid): Sigmoid()
          )
          (odefunc): RegularizedODEfunc(
            (odefunc): ODEfu

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

Epoch 0001 | Time 112.6362, Epoch Time 1443.4331(1443.4331), Bit/dim 7.0173(best: inf), Bit/dim Marginal 7.0170(best: inf), Xent 2.0832, Loss 8.0589, Error 0.7076(best: inf)
===> Using batch size 900. Total 102 iterations/epoch.
Iter 0110 | Time 13.7558(13.8841) | Bit/dim 6.9789(7.3713) | Xent 2.0808(2.0931) | Loss 18.1608(19.3644) | Error 0.6956(0.7078) Steps 568(525.99) | Grad Norm 8.7333(6.0047) | Total Time 0.00(0.00)
Iter 0120 | Time 13.1449(13.8518) | Bit/dim 6.9533(7.2658) | Xent 2.0297(2.0841) | Loss 17.7937(18.9710) | Error 0.6867(0.7049) Steps 532(529.23) | Grad Norm 3.5183(6.0684) | Total Time 0.00(0.00)
Iter 0130 | Time 13.7124(13.8454) | Bit/dim 6.9220(7.1794) | Xent 2.0018(2.0728) | Loss 17.7757(18.6700) | Error 0.6711(0.7004) Steps 556(530.64) | Grad Norm 4.4384(6.6063) | Total Time 0.00(0.00)
Iter 0140 | Time 14.0008(13.8606) | Bit/dim 6.8954(7.1065) | Xent 1.9783(2.0604) | Loss 17.7023(18.4334) | Error 0.6378(0.6931) Steps 568(535.95) | Grad Norm 4.1636(6.7684) | Total

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

Epoch 0002 | Time 90.0236, Epoch Time 1504.8699(1445.2762), Bit/dim 6.0295(best: 7.0173), Bit/dim Marginal 6.0230(best: 7.0170), Xent 2.0937, Loss 7.0763, Error 0.7693(best: 0.7076)
===> Using batch size 900. Total 102 iterations/epoch.
Iter 0210 | Time 13.8593(13.6783) | Bit/dim 5.9285(6.4170) | Xent 2.0526(2.0408) | Loss 15.7108(17.3935) | Error 0.6956(0.7014) Steps 520(545.81) | Grad Norm 31.3932(43.8032) | Total Time 0.00(0.00)
Iter 0220 | Time 14.1221(13.6635) | Bit/dim 5.8200(6.2710) | Xent 2.0506(2.0302) | Loss 15.5338(16.9028) | Error 0.7600(0.6949) Steps 556(546.70) | Grad Norm 116.4539(44.2989) | Total Time 0.00(0.00)
Iter 0230 | Time 14.2682(13.8094) | Bit/dim 5.8839(6.2061) | Xent 2.0248(2.0502) | Loss 15.6498(16.6613) | Error 0.6533(0.7044) Steps 544(550.05) | Grad Norm 18.6582(59.6964) | Total Time 0.00(0.00)
Iter 0240 | Time 13.5713(13.6403) | Bit/dim 5.7707(6.1071) | Xent 1.9833(2.0385) | Loss 15.2934(16.3370) | Error 0.6956(0.6953) Steps 544(544.90) | Grad Norm 10.8949

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

Epoch 0003 | Time 78.5679, Epoch Time 1471.2933(1446.0567), Bit/dim 5.5536(best: 6.0295), Bit/dim Marginal 5.5309(best: 6.0230), Xent 1.9703, Loss 6.5388, Error 0.6812(best: 0.7076)
===> Using batch size 900. Total 102 iterations/epoch.
Iter 0310 | Time 12.7070(13.0968) | Bit/dim 5.5288(5.6447) | Xent 1.8612(1.8844) | Loss 14.6204(15.6021) | Error 0.6400(0.6231) Steps 538(532.83) | Grad Norm 53.8815(27.2287) | Total Time 0.00(0.00)
Iter 0320 | Time 13.0115(13.0915) | Bit/dim 5.4953(5.6144) | Xent 1.9449(1.8957) | Loss 14.6321(15.3638) | Error 0.6644(0.6360) Steps 544(531.62) | Grad Norm 46.1753(36.4775) | Total Time 0.00(0.00)
Iter 0330 | Time 13.2089(13.0739) | Bit/dim 5.4982(5.5804) | Xent 1.8462(1.8858) | Loss 14.7149(15.1478) | Error 0.6289(0.6317) Steps 520(529.61) | Grad Norm 18.9124(32.3898) | Total Time 0.00(0.00)
Iter 0340 | Time 13.9330(13.1035) | Bit/dim 5.4522(5.5498) | Xent 1.7239(1.8642) | Loss 14.4411(14.9657) | Error 0.5733(0.6198) Steps 550(530.21) | Grad Norm 12.4184(

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

Epoch 0004 | Time 78.8902, Epoch Time 1520.3214(1448.2846), Bit/dim 5.2206(best: 5.5536), Bit/dim Marginal 5.1792(best: 5.5309), Xent 1.9436, Loss 6.1924, Error 0.6688(best: 0.6812)
===> Using batch size 900. Total 102 iterations/epoch.
Iter 0410 | Time 13.9197(13.6569) | Bit/dim 5.2087(5.3101) | Xent 1.5907(1.7229) | Loss 13.6514(14.8018) | Error 0.5356(0.5824) Steps 586(549.10) | Grad Norm 28.3572(27.2921) | Total Time 0.00(0.00)
Iter 0420 | Time 13.7557(13.6665) | Bit/dim 5.1387(5.2751) | Xent 1.6029(1.7021) | Loss 13.6326(14.5298) | Error 0.5489(0.5767) Steps 544(549.51) | Grad Norm 38.2029(26.7013) | Total Time 0.00(0.00)
Iter 0430 | Time 13.5518(13.7086) | Bit/dim 5.1510(5.2485) | Xent 1.7017(1.6944) | Loss 13.6734(14.3321) | Error 0.6067(0.5778) Steps 562(548.84) | Grad Norm 42.9912(27.1335) | Total Time 0.00(0.00)
Iter 0440 | Time 13.3353(13.6329) | Bit/dim 5.1321(5.2233) | Xent 1.6754(1.6805) | Loss 13.5364(14.1527) | Error 0.5889(0.5763) Steps 538(546.84) | Grad Norm 38.9261(

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

Epoch 0005 | Time 82.2488, Epoch Time 1582.1022(1452.2992), Bit/dim 4.9608(best: 5.2206), Bit/dim Marginal 4.9168(best: 5.1792), Xent 1.9040, Loss 5.9128, Error 0.6631(best: 0.6688)
===> Using batch size 900. Total 102 iterations/epoch.
Iter 0520 | Time 13.6995(13.9101) | Bit/dim 4.8817(4.9923) | Xent 1.5061(1.6005) | Loss 13.0218(13.8474) | Error 0.5289(0.5539) Steps 550(547.29) | Grad Norm 29.5670(30.1735) | Total Time 0.00(0.00)
Iter 0530 | Time 14.0410(13.9224) | Bit/dim 4.8692(4.9699) | Xent 1.5086(1.5868) | Loss 12.8701(13.6324) | Error 0.5111(0.5497) Steps 526(548.98) | Grad Norm 26.2373(31.9331) | Total Time 0.00(0.00)
Iter 0540 | Time 13.5261(13.9309) | Bit/dim 4.8455(4.9435) | Xent 1.5126(1.5854) | Loss 12.7994(13.4721) | Error 0.5044(0.5498) Steps 538(550.64) | Grad Norm 17.3716(30.9508) | Total Time 0.00(0.00)
Iter 0550 | Time 14.1448(13.9741) | Bit/dim 4.8302(4.9199) | Xent 1.5140(1.5687) | Loss 12.8506(13.3131) | Error 0.5244(0.5435) Steps 574(553.10) | Grad Norm 53.1258(

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

Epoch 0006 | Time 82.4160, Epoch Time 1638.6074(1457.8884), Bit/dim 4.7528(best: 4.9608), Bit/dim Marginal 4.7025(best: 4.9168), Xent 1.8888, Loss 5.6972, Error 0.6586(best: 0.6631)
===> Using batch size 900. Total 102 iterations/epoch.
Iter 0620 | Time 14.8368(14.4802) | Bit/dim 4.7721(4.7998) | Xent 1.5570(1.5171) | Loss 12.8629(13.4193) | Error 0.5511(0.5303) Steps 562(566.61) | Grad Norm 44.2861(30.5818) | Total Time 0.00(0.00)
Iter 0630 | Time 14.9049(14.5184) | Bit/dim 4.7645(4.7928) | Xent 1.6161(1.5295) | Loss 12.8767(13.2664) | Error 0.5600(0.5351) Steps 586(566.72) | Grad Norm 30.6493(32.2545) | Total Time 0.00(0.00)
Iter 0640 | Time 14.5847(14.6224) | Bit/dim 4.7374(4.7744) | Xent 1.4690(1.5250) | Loss 12.6107(13.0989) | Error 0.5244(0.5330) Steps 532(568.23) | Grad Norm 19.5155(29.2788) | Total Time 0.00(0.00)
Iter 0650 | Time 14.3715(14.6964) | Bit/dim 4.6636(4.7523) | Xent 1.4289(1.5051) | Loss 12.5173(12.9525) | Error 0.4933(0.5252) Steps 598(568.76) | Grad Norm 27.2042(

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

Epoch 0007 | Time 86.1988, Epoch Time 1700.1266(1465.1556), Bit/dim 4.6509(best: 4.7528), Bit/dim Marginal 4.6039(best: 4.7025), Xent 1.8804, Loss 5.5911, Error 0.6595(best: 0.6586)
===> Using batch size 900. Total 102 iterations/epoch.
Iter 0720 | Time 15.1702(14.8649) | Bit/dim 4.6661(4.6689) | Xent 1.4263(1.4749) | Loss 12.4391(13.1648) | Error 0.4911(0.5198) Steps 616(583.44) | Grad Norm 26.9141(29.7631) | Total Time 0.00(0.00)
Iter 0730 | Time 15.5895(14.9936) | Bit/dim 4.6121(4.6523) | Xent 1.3454(1.4562) | Loss 12.4812(12.9493) | Error 0.4711(0.5117) Steps 592(583.74) | Grad Norm 17.3455(26.7814) | Total Time 0.00(0.00)
Iter 0740 | Time 15.0001(14.9624) | Bit/dim 4.5791(4.6374) | Xent 1.3452(1.4409) | Loss 12.1197(12.7697) | Error 0.4867(0.5074) Steps 604(585.91) | Grad Norm 13.5189(24.2124) | Total Time 0.00(0.00)
Iter 0750 | Time 14.8927(15.0117) | Bit/dim 4.6449(4.6250) | Xent 1.4643(1.4247) | Loss 12.3104(12.6361) | Error 0.5222(0.5004) Steps 562(586.61) | Grad Norm 34.4633(

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

Epoch 0008 | Time 84.0079, Epoch Time 1699.5381(1472.1870), Bit/dim 4.5634(best: 4.6509), Bit/dim Marginal 4.5216(best: 4.6039), Xent 1.7639, Loss 5.4453, Error 0.6180(best: 0.6586)
===> Using batch size 900. Total 102 iterations/epoch.
Iter 0820 | Time 15.0094(15.1210) | Bit/dim 4.4834(4.5504) | Xent 1.3547(1.3910) | Loss 12.1104(12.9032) | Error 0.4667(0.4900) Steps 592(594.54) | Grad Norm 25.2815(22.4873) | Total Time 0.00(0.00)
Iter 0830 | Time 15.1973(15.1187) | Bit/dim 4.5023(4.5375) | Xent 1.3936(1.3875) | Loss 12.0795(12.7005) | Error 0.4733(0.4872) Steps 622(596.37) | Grad Norm 26.6487(22.8464) | Total Time 0.00(0.00)
Iter 0840 | Time 15.1117(15.1498) | Bit/dim 4.5158(4.5261) | Xent 1.3991(1.3802) | Loss 12.0700(12.5281) | Error 0.4956(0.4856) Steps 616(601.02) | Grad Norm 22.8175(22.1435) | Total Time 0.00(0.00)
Iter 0850 | Time 15.8589(15.1684) | Bit/dim 4.4632(4.5120) | Xent 1.3604(1.3728) | Loss 12.0831(12.3851) | Error 0.4667(0.4828) Steps 604(601.82) | Grad Norm 31.0626(

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

Epoch 0009 | Time 96.5742, Epoch Time 1686.8458(1478.6268), Bit/dim 4.4611(best: 4.5634), Bit/dim Marginal 4.4266(best: 4.5216), Xent 1.7940, Loss 5.3581, Error 0.6412(best: 0.6180)
===> Using batch size 900. Total 102 iterations/epoch.
Iter 0930 | Time 14.6406(15.0530) | Bit/dim 4.4298(4.4333) | Xent 1.2854(1.3479) | Loss 11.8524(12.4525) | Error 0.4444(0.4735) Steps 598(599.94) | Grad Norm 14.9556(22.7463) | Total Time 0.00(0.00)
Iter 0940 | Time 14.7519(15.0939) | Bit/dim 4.3744(4.4199) | Xent 1.2074(1.3322) | Loss 11.7982(12.2681) | Error 0.4178(0.4691) Steps 592(599.84) | Grad Norm 13.3621(20.0963) | Total Time 0.00(0.00)
Iter 0950 | Time 14.8434(15.0617) | Bit/dim 4.3709(4.4048) | Xent 1.1440(1.3144) | Loss 11.6152(12.1044) | Error 0.4378(0.4651) Steps 586(597.46) | Grad Norm 11.5118(17.9635) | Total Time 0.00(0.00)
Iter 0960 | Time 16.0128(15.0641) | Bit/dim 4.6142(4.4013) | Xent 1.4269(1.3116) | Loss 12.3409(12.0181) | Error 0.4978(0.4631) Steps 652(598.53) | Grad Norm 33.0322(

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

Epoch 0010 | Time 84.7088, Epoch Time 1674.5948(1484.5058), Bit/dim 4.3037(best: 4.4611), Bit/dim Marginal 4.2791(best: 4.4266), Xent 1.7054, Loss 5.1564, Error 0.6019(best: 0.6180)
===> Using batch size 900. Total 102 iterations/epoch.
