In [1]:
import os
os.environ['CUDA_VISIBLE_DEVICES']='0,1,2,3'

In [ ]:
%run -p ./mnist_train.py --model 'convlstm' --input-frames 10 --future_frames 10 --output-frames 19 --data-path './dataset' --model-path './models' --model-path './results'  

> /tancode/repos/tan-ffjord/moving_mnist/data_provider/mnist.py(24)load()
     23         dat_1 = np.load(self.paths[0])
---> 24         for key in dat_1.keys():
     25             self.data[key] = dat_1[key]



ipdb>  key


'clips'


ipdb>  self.data[key]


array([[[     0,     10],
        [    20,     10],
        [    40,     10],
        ...,
        [199940,     10],
        [199960,     10],
        [199980,     10]],

       [[    10,     10],
        [    30,     10],
        [    50,     10],
        ...,
        [199950,     10],
        [199970,     10],
        [199990,     10]]], dtype=int32)


ipdb>  c


> /tancode/repos/tan-ffjord/moving_mnist/data_provider/mnist.py(24)load()
     23         dat_1 = np.load(self.paths[0])
---> 24         for key in dat_1.keys():
     25             self.data[key] = dat_1[key]



ipdb>  key


'dims'


ipdb>  self.data[key]


array([[ 1, 64, 64]], dtype=int32)


ipdb>  c


> /tancode/repos/tan-ffjord/moving_mnist/data_provider/mnist.py(24)load()
     23         dat_1 = np.load(self.paths[0])
---> 24         for key in dat_1.keys():
     25             self.data[key] = dat_1[key]



ipdb>  key


'input_raw_data'


ipdb>  self.data[key]


array([[[[0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         ...,
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.]]],


       [[[0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         ...,
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.]]],


       [[[0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         ...,
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.]]],


       ...,


       [[[0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         ...,
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.]

ipdb>  self.data[key].shape


(200000, 1, 64, 64)


ipdb>  c


load ./dataset/moving-mnist-train.npz
> /tancode/repos/tan-ffjord/moving_mnist/data_provider/mnist.py(24)load()
     23         dat_1 = np.load(self.paths[0])
---> 24         for key in dat_1.keys():
     25             self.data[key] = dat_1[key]



ipdb>  key


'clips'


ipdb>  self.data[key]


array([[[    0,    10],
        [   20,    10],
        [   40,    10],
        ...,
        [39940,    10],
        [39960,    10],
        [39980,    10]],

       [[   10,    10],
        [   30,    10],
        [   50,    10],
        ...,
        [39950,    10],
        [39970,    10],
        [39990,    10]]], dtype=int32)


ipdb>  self.data[key].shape


(2, 2000, 2)


ipdb>  self.data[key][:,0,1]


array([10, 10], dtype=int32)


ipdb>  self.data[key][:,0,0]


array([ 0, 10], dtype=int32)
